version: "3.7"

services:
    # image project
    app:
        #imagem personalizada
        build:
            context: .  # em qual diretorio as configurações estão
            dockerfile: Dockerfile   # nome do arquivo dockerfile
        image: clecyo7/laravel9-app  #imagem personalizada
        restart: unless-stopped   # restart apenas quando parar
        working_dir: /var/www/   #onde a aplicação vai rodar
        volumes:
            - ./:/var/www   #pegando os arquivos locais do laravel e jogando para dentro do working
        depends_on:
            - redis
        networks:
            - laravel-9   #rede que será rodado

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # db mysql
    mysql:
        container_name: base-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel-9

    # queue
    queue:
        image: easyfood/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    # redis
    redis:
        image: redis:latest
        ports:
          - "6379:6379"
        networks:
            - laravel-9

#rede que será rodado
networks:
    laravel-9:
        driver: bridge
